not_using:
gmail:
    task_label: task_inbox
    note_label: note_inbox
gdrive:
    folder_id: 
notion:
    token: 
    task_db: 
    note_db: 
    tag: Email
openai:
    api: 
    model: gpt-4o
    use_gpt: true
    input_cost_per_mil: 5
    output_cost_per_mil: 15